/*
 * expert.ai Natural Language API
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * OpenAPI spec version: v2
 * Contact: api.inquiry@expert.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package my.rest.api.nl.bean;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Available contexts
 */
public class ContextsResponse {

  private List<ContextInfo> contexts = null;

  public ContextsResponse contexts(List<ContextInfo> contexts) {
    this.contexts = contexts;
    return this;
  }

  public ContextsResponse addContextsItem(ContextInfo contextsItem) {
    if (this.contexts == null) {
      this.contexts = new ArrayList<ContextInfo>();
    }
    this.contexts.add(contextsItem);
    return this;
  }

   /**
   * List of contexts&#x27; information
   * @return contexts
  **/

  public List<ContextInfo> getContexts() {
    return contexts;
  }

  public void setContexts(List<ContextInfo> contexts) {
    this.contexts = contexts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContextsResponse contextsResponse = (ContextsResponse) o;
    return Objects.equals(this.contexts, contextsResponse.contexts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contexts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContextsResponse {\n");
    
    sb.append("    contexts: ").append(toIndentedString(contexts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
