/*
 * expert.ai Natural Language API
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * OpenAPI spec version: v2
 * Contact: api.inquiry@expert.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package my.rest.api.nl.bean;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Information about a supported language and available analyses
 */
public class ContextLanguageInfo {

  private String code = null;


  private String name = null;


  private List<String> analyses = null;

  public ContextLanguageInfo code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Language code
   * @return code
  **/

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ContextLanguageInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Language name
   * @return name
  **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ContextLanguageInfo analyses(List<String> analyses) {
    this.analyses = analyses;
    return this;
  }

  public ContextLanguageInfo addAnalysesItem(String analysesItem) {
    if (this.analyses == null) {
      this.analyses = new ArrayList<String>();
    }
    this.analyses.add(analysesItem);
    return this;
  }

   /**
   * Available analyses
   * @return analyses
  **/

  public List<String> getAnalyses() {
    return analyses;
  }

  public void setAnalyses(List<String> analyses) {
    this.analyses = analyses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContextLanguageInfo contextLanguageInfo = (ContextLanguageInfo) o;
    return Objects.equals(this.code, contextLanguageInfo.code) &&
        Objects.equals(this.name, contextLanguageInfo.name) &&
        Objects.equals(this.analyses, contextLanguageInfo.analyses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, name, analyses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContextLanguageInfo {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    analyses: ").append(toIndentedString(analyses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
