/*
 * expert.ai Natural Language API
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * OpenAPI spec version: v2
 * Contact: api.inquiry@expert.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package my.rest.api.nl.bean;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Entity info
 */
public class Entity {

  private String type = null;

  private String lemma = null;

  private Long syncon = null;

  private List<DocumentPosition> positions = null;

  private Long relevance = null;

  private List<InferredAttribute> attributes = null;

  public Entity type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Entity type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Entity lemma(String lemma) {
    this.lemma = lemma;
    return this;
  }

   /**
   * Base form (lemma) of the entity name
   * @return lemma
  **/
  public String getLemma() {
    return lemma;
  }

  public void setLemma(String lemma) {
    this.lemma = lemma;
  }

  public Entity syncon(Long syncon) {
    this.syncon = syncon;
    return this;
  }

   /**
   * ID used to look up Knowledge Graph data in the &#x60;knowledge&#x60; array
   * @return syncon
  **/
  public Long getSyncon() {
    return syncon;
  }

  public void setSyncon(Long syncon) {
    this.syncon = syncon;
  }

  public Entity positions(List<DocumentPosition> positions) {
    this.positions = positions;
    return this;
  }

  public Entity addPositionsItem(DocumentPosition positionsItem) {
    if (this.positions == null) {
      this.positions = new ArrayList<DocumentPosition>();
    }
    this.positions.add(positionsItem);
    return this;
  }

   /**
   * Positions of the entity&#x27;s mentions
   * @return positions
  **/
  public List<DocumentPosition> getPositions() {
    return positions;
  }

  public void setPositions(List<DocumentPosition> positions) {
    this.positions = positions;
  }

  public Entity relevance(Long relevance) {
    this.relevance = relevance;
    return this;
  }

   /**
   * Entity relevance
   * @return relevance
  **/
  public Long getRelevance() {
    return relevance;
  }

  public void setRelevance(Long relevance) {
    this.relevance = relevance;
  }

  public Entity attributes(List<InferredAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public Entity addAttributesItem(InferredAttribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<InferredAttribute>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Entity attributes inferred from the context or from the Knowledge Graph
   * @return attributes
  **/
  public List<InferredAttribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<InferredAttribute> attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entity entity = (Entity) o;
    return Objects.equals(this.type, entity.type) &&
        Objects.equals(this.lemma, entity.lemma) &&
        Objects.equals(this.syncon, entity.syncon) &&
        Objects.equals(this.positions, entity.positions) &&
        Objects.equals(this.relevance, entity.relevance) &&
        Objects.equals(this.attributes, entity.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, lemma, syncon, positions, relevance, attributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Entity {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    lemma: ").append(toIndentedString(lemma)).append("\n");
    sb.append("    syncon: ").append(toIndentedString(syncon)).append("\n");
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("    relevance: ").append(toIndentedString(relevance)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
