/*
 * expert.ai Natural Language API
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * OpenAPI spec version: v2
 * Contact: api.inquiry@expert.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package my.rest.api.nl.bean;

import java.util.Objects;
/**
 * Main sentence
 */
public class MainSentence {
  private String value = null;

  private Float score = null;

  private Long start = null;

  private Long end = null;

  public MainSentence value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Sentence text
   * @return value
  **/
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public MainSentence score(Float score) {
    this.score = score;
    return this;
  }

   /**
   * Score assigned to the sentence to represent its relevance
   * @return score
  **/
  public Float getScore() {
    return score;
  }

  public void setScore(Float score) {
    this.score = score;
  }

  public MainSentence start(Long start) {
    this.start = start;
    return this;
  }

   /**
   * Zero-based position of the first character of the sentence
   * @return start
  **/
  public Long getStart() {
    return start;
  }

  public void setStart(Long start) {
    this.start = start;
  }

  public MainSentence end(Long end) {
    this.end = end;
    return this;
  }

   /**
   * Zero-based position of the first character after the sentence
   * @return end
  **/
  public Long getEnd() {
    return end;
  }

  public void setEnd(Long end) {
    this.end = end;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MainSentence mainSentence = (MainSentence) o;
    return Objects.equals(this.value, mainSentence.value) &&
        Objects.equals(this.score, mainSentence.score) &&
        Objects.equals(this.start, mainSentence.start) &&
        Objects.equals(this.end, mainSentence.end);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, score, start, end);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MainSentence {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
