/*
 * expert.ai Natural Language API
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * OpenAPI spec version: v2
 * Contact: api.inquiry@expert.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package my.rest.api.nl.bean;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Paragraph info
 */
public class Paragraph {

  private Long start = null;

  private Long end = null;

  private List<Integer> sentences = null;

  public Paragraph start(Long start) {
    this.start = start;
    return this;
  }

   /**
   * Zero-based position of the first character of the paragraph
   * @return start
  **/
  public Long getStart() {
    return start;
  }

  public void setStart(Long start) {
    this.start = start;
  }

  public Paragraph end(Long end) {
    this.end = end;
    return this;
  }

   /**
   * Zero-based position of the first character after the paragraph
   * @return end
  **/
  public Long getEnd() {
    return end;
  }

  public void setEnd(Long end) {
    this.end = end;
  }

  public Paragraph sentences(List<Integer> sentences) {
    this.sentences = sentences;
    return this;
  }

  public Paragraph addSentencesItem(Integer sentencesItem) {
    if (this.sentences == null) {
      this.sentences = new ArrayList<Integer>();
    }
    this.sentences.add(sentencesItem);
    return this;
  }

   /**
   * Indexes (in the &#x60;sentences&#x60; array) of the sentences that make up the paragraph
   * @return sentences
  **/
  public List<Integer> getSentences() {
    return sentences;
  }

  public void setSentences(List<Integer> sentences) {
    this.sentences = sentences;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Paragraph paragraph = (Paragraph) o;
    return Objects.equals(this.start, paragraph.start) &&
        Objects.equals(this.end, paragraph.end) &&
        Objects.equals(this.sentences, paragraph.sentences);
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, end, sentences);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Paragraph {\n");
    
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    sentences: ").append(toIndentedString(sentences)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
