/*
 * expert.ai Natural Language API
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * OpenAPI spec version: v2
 * Contact: api.inquiry@expert.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package my.rest.api.nl.bean;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * In a relation, a term that&#x27;s directly or indirectly related to the verb
 */
public class RelatedItem {
  private String relation = null;

  private String text = null;

  private String lemma = null;

  private Long syncon = null;

  private VirtualSyncon vsyn = null;

  private String type = null;

  private Long phrase = null;

  private Long relevance = null;

  private List<RelatedItem> related = null;

  public RelatedItem relation(String relation) {
    this.relation = relation;
    return this;
  }

   /**
   * Verb-item relation
   * @return relation
  **/
  public String getRelation() {
    return relation;
  }

  public void setRelation(String relation) {
    this.relation = relation;
  }

  public RelatedItem text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Item text
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public RelatedItem lemma(String lemma) {
    this.lemma = lemma;
    return this;
  }

   /**
   * Lemma
   * @return lemma
  **/
  public String getLemma() {
    return lemma;
  }

  public void setLemma(String lemma) {
    this.lemma = lemma;
  }

  public RelatedItem syncon(Long syncon) {
    this.syncon = syncon;
    return this;
  }

   /**
   * ID used to look up Knowledge Graph data in the &#x60;knowledge&#x60; array
   * @return syncon
  **/
  public Long getSyncon() {
    return syncon;
  }

  public void setSyncon(Long syncon) {
    this.syncon = syncon;
  }

  public RelatedItem vsyn(VirtualSyncon vsyn) {
    this.vsyn = vsyn;
    return this;
  }

   /**
   * Get vsyn
   * @return vsyn
  **/
  public VirtualSyncon getVsyn() {
    return vsyn;
  }

  public void setVsyn(VirtualSyncon vsyn) {
    this.vsyn = vsyn;
  }

  public RelatedItem type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public RelatedItem phrase(Long phrase) {
    this.phrase = phrase;
    return this;
  }

   /**
   * Phrase index in the &#x60;phrases&#x60; array
   * @return phrase
  **/
  public Long getPhrase() {
    return phrase;
  }

  public void setPhrase(Long phrase) {
    this.phrase = phrase;
  }

  public RelatedItem relevance(Long relevance) {
    this.relevance = relevance;
    return this;
  }

   /**
   * Relevance
   * @return relevance
  **/
  public Long getRelevance() {
    return relevance;
  }

  public void setRelevance(Long relevance) {
    this.relevance = relevance;
  }

  public RelatedItem related(List<RelatedItem> related) {
    this.related = related;
    return this;
  }

  public RelatedItem addRelatedItem(RelatedItem relatedItem) {
    if (this.related == null) {
      this.related = new ArrayList<RelatedItem>();
    }
    this.related.add(relatedItem);
    return this;
  }

   /**
   * Related terms
   * @return related
  **/
  public List<RelatedItem> getRelated() {
    return related;
  }

  public void setRelated(List<RelatedItem> related) {
    this.related = related;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelatedItem relatedItem = (RelatedItem) o;
    return Objects.equals(this.relation, relatedItem.relation) &&
        Objects.equals(this.text, relatedItem.text) &&
        Objects.equals(this.lemma, relatedItem.lemma) &&
        Objects.equals(this.syncon, relatedItem.syncon) &&
        Objects.equals(this.vsyn, relatedItem.vsyn) &&
        Objects.equals(this.type, relatedItem.type) &&
        Objects.equals(this.phrase, relatedItem.phrase) &&
        Objects.equals(this.relevance, relatedItem.relevance) &&
        Objects.equals(this.related, relatedItem.related);
  }

  @Override
  public int hashCode() {
    return Objects.hash(relation, text, lemma, syncon, vsyn, type, phrase, relevance, related);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelatedItem {\n");
    
    sb.append("    relation: ").append(toIndentedString(relation)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    lemma: ").append(toIndentedString(lemma)).append("\n");
    sb.append("    syncon: ").append(toIndentedString(syncon)).append("\n");
    sb.append("    vsyn: ").append(toIndentedString(vsyn)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    phrase: ").append(toIndentedString(phrase)).append("\n");
    sb.append("    relevance: ").append(toIndentedString(relevance)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
