/*
 * expert.ai Natural Language API
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * OpenAPI spec version: v2
 * Contact: api.inquiry@expert.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package my.rest.api.nl.bean;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Verb-mediated relation
 */
public class Relation {
  private RelationVerb verb = null;

  private List<RelatedItem> related = null;

  public Relation verb(RelationVerb verb) {
    this.verb = verb;
    return this;
  }

   /**
   * Get verb
   * @return verb
  **/
  public RelationVerb getVerb() {
    return verb;
  }

  public void setVerb(RelationVerb verb) {
    this.verb = verb;
  }

  public Relation related(List<RelatedItem> related) {
    this.related = related;
    return this;
  }

  public Relation addRelatedItem(RelatedItem relatedItem) {
    if (this.related == null) {
      this.related = new ArrayList<RelatedItem>();
    }
    this.related.add(relatedItem);
    return this;
  }

   /**
   * Related items
   * @return related
  **/
  public List<RelatedItem> getRelated() {
    return related;
  }

  public void setRelated(List<RelatedItem> related) {
    this.related = related;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Relation relation = (Relation) o;
    return Objects.equals(this.verb, relation.verb) &&
        Objects.equals(this.related, relation.related);
  }

  @Override
  public int hashCode() {
    return Objects.hash(verb, related);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Relation {\n");
    
    sb.append("    verb: ").append(toIndentedString(verb)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
