/*
 * expert.ai Natural Language API
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * OpenAPI spec version: v2
 * Contact: api.inquiry@expert.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package my.rest.api.nl.bean;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Sentence info
 */
public class Sentence {
	
  private Long start = null;

  private Long end = null;

  private List<Integer> phrases = null;

  public Sentence start(Long start) {
    this.start = start;
    return this;
  }

   /**
   * Zero-based position of the first character of the sentence
   * @return start
  **/
  public Long getStart() {
    return start;
  }

  public void setStart(Long start) {
    this.start = start;
  }

  public Sentence end(Long end) {
    this.end = end;
    return this;
  }

   /**
   * Zero-based position of the first character after the sentence
   * @return end
  **/
  public Long getEnd() {
    return end;
  }

  public void setEnd(Long end) {
    this.end = end;
  }

  public Sentence phrases(List<Integer> phrases) {
    this.phrases = phrases;
    return this;
  }

  public Sentence addPhrasesItem(Integer phrasesItem) {
    if (this.phrases == null) {
      this.phrases = new ArrayList<Integer>();
    }
    this.phrases.add(phrasesItem);
    return this;
  }

   /**
   * Indexes (in the &#x60;phrases&#x60; array) of the phrases that make up the sentence
   * @return phrases
  **/
  public List<Integer> getPhrases() {
    return phrases;
  }

  public void setPhrases(List<Integer> phrases) {
    this.phrases = phrases;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sentence sentence = (Sentence) o;
    return Objects.equals(this.start, sentence.start) &&
        Objects.equals(this.end, sentence.end) &&
        Objects.equals(this.phrases, sentence.phrases);
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, end, phrases);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sentence {\n");
    
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    phrases: ").append(toIndentedString(phrases)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
