/*
 * expert.ai Natural Language API
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * OpenAPI spec version: v2
 * Contact: api.inquiry@expert.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package my.rest.api.nl.bean;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * A taxonomy&#x27;s categories tree
 */
public class Taxonomy {
  private String namespace = null;

  private List<TaxonomyCategory> taxonomy = null;

  public Taxonomy namespace(String namespace) {
    this.namespace = namespace;
    return this;
  }

   /**
   * Name of the software package containing the reference taxonomy
   * @return namespace
  **/
  public String getNamespace() {
    return namespace;
  }

  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }

  public Taxonomy taxonomy(List<TaxonomyCategory> taxonomy) {
    this.taxonomy = taxonomy;
    return this;
  }

  public Taxonomy addTaxonomyItem(TaxonomyCategory taxonomyItem) {
    if (this.taxonomy == null) {
      this.taxonomy = new ArrayList<TaxonomyCategory>();
    }
    this.taxonomy.add(taxonomyItem);
    return this;
  }

   /**
   * Categories tree
   * @return taxonomy
  **/
  public List<TaxonomyCategory> getTaxonomy() {
    return taxonomy;
  }

  public void setTaxonomy(List<TaxonomyCategory> taxonomy) {
    this.taxonomy = taxonomy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Taxonomy taxonomy = (Taxonomy) o;
    return Objects.equals(this.namespace, taxonomy.namespace) &&
        Objects.equals(this.taxonomy, taxonomy.taxonomy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(namespace, taxonomy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Taxonomy {\n");
    
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    taxonomy: ").append(toIndentedString(taxonomy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
