/*
 * expert.ai Natural Language API
 * Natural Language API provides a comprehensive set of natural language understanding capabilities based on expert.ai technology: <ul>   <li>Text subdivision</li>   <li>Part-of-speech tagging</li>   <li>Syntactic analysis</li>   <li>Lemmatization</li>   <li>Keyphrase extraction</li>   <li>Semantic analysis</li>   <li>Named entity recognition</li>   <li>Relation extraction</li>   <li>Sentiment analysis</li>   <li>Classification</li> </ul> 
 *
 * OpenAPI spec version: v2
 * Contact: api.inquiry@expert.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package my.rest.api.nl.bean;

import java.util.Objects;
/**
 * A concept that does not exist in the Knowledge Graph but heuristics recognized as a type of a known parent concept.
 */
public class VirtualSyncon {
  private Long id = null;

  private Long parent = null;

  public VirtualSyncon id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * ID used to mark all the occurrences of the virtual concept in the text
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public VirtualSyncon parent(Long parent) {
    this.parent = parent;
    return this;
  }

   /**
   * Parent concept; ID is used to look up Knowledge Graph data in the &#x60;knowledge&#x60; array
   * @return parent
  **/
  public Long getParent() {
    return parent;
  }

  public void setParent(Long parent) {
    this.parent = parent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualSyncon virtualSyncon = (VirtualSyncon) o;
    return Objects.equals(this.id, virtualSyncon.id) &&
        Objects.equals(this.parent, virtualSyncon.parent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, parent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualSyncon {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
